version: '3'
services:
  docker-host:
    # https://github.com/qoomon/docker-host
    # docker-host 容器，主要用来兼容不同系统（macos、linux）获取宿主机 IP。
    image: qoomon/docker-host
    container_name: docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  open-dingtalk-pierced:
    build: 
      context: .
    image: zhb127/open-dingtalk-pierced
    container_name: open-dingtalk-pierced
    restart: always
    depends_on:
      - docker-host
    environment:
      SUBDOMAIN: "zhb127-test"
      PORT: docker-host:80
    ports:
      - "4040:4040"