version: '3'
services:
  dockerhost:
    # https://github.com/qoomon/docker-host
    # dockerhost 容器，主要用来兼容不同系统（macos、linux）获取宿主机 IP。
    image: qoomon/docker-host
    container_name: dockerhost
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  open-dingtalk-pierced:
    image: zhb127/open-dingtalk-pierced
    container_name: open-dingtalk-pierced
    restart: always
    depends_on:
      - dockerhost
    environment:
      NGROK_SUBDOMAIN: "zhb127-local-test"
      NGROK_PORT: dockerhost:8082
    ports:
      - "4040:4040"